version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    volumes:
      - .rabbitmq:/var/libs/rabbitmq/mnesiaa
    ports:
      - "15672:15672"
      - "5672:5672"
